import type { Metadata } from "next";
import Script from 'next/script';
// import { Geist, Geist_Mono, Inter } from "next/font/google";
// import { Pixelify_Sans } from "next/font/google";
import {Providers} from './Providers'
import Navigation from './components/Navigation'
import "./globals.css";

// const inter = Inter({ 
//   subsets: ['latin'],
//   variable: '--font-inter', // Creamos una variable CSS
// });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const pixelify = Pixelify_Sans({
//   variable: "--font-pixelify",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // <html lang="en" className={`${pixelify.className}`}>
    <html lang="en" className={``}>
    <head>
      <Script
        async
        src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9158230735641941"
        crossOrigin="anonymous"
        strategy="afterInteractive"
      />
    </head>
      <body className="scrollTransaction relative overflow-y-auto md:overflow-y-hidden overflow-x-hidden">
        <Providers>
          <Navigation /> {/* Ahora sí funcionará como Server Component */}
          <main className="">{children}</main>
        </Providers>
      </body>
    </html>
  )
}
