import type { Metadata } from "next";
// import { Geist, Geist_Mono, Inter } from "next/font/google";
import {Providers} from './Providers'
import Navigation from './components/Navigation'
import "./globals.css";

// const inter = Inter({ 
//   subsets: ['latin'],
//   variable: '--font-inter', // Creamos una variable CSS
// });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={``}>
      <body className="h-screen border-2 border-white/30 relative overflow-hidden">
        <Providers>
          <Navigation /> {/* Ahora sí funcionará como Server Component */}
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
